### ISSUE TITLE
error installing i-haklab

### ISSUE THREAD

**Issue by y0ur3nz** [ivam3/i-Haklab#11]
I ran the command $ apt install i-haklab and it worked 

![Screenshot_2023-06-16-02-09-19-94_84d3000e3f4017145260f7618db1d683](https://github.com/ivam3/i-Haklab/assets/136704583/9037353e-f198-4f18-86fe-514439c11b8d)

same when I installed i-haklab with git

**Comment by y0ur3nz** [comment]
pls solve this

**Comment by ivam3** [comment]
Issue was Resolved In the last updated at version 3.7.1
