### ISSUE TITLE
I have an issue with ChatGPT after adding API key: The model `text-davinci-003` has been deprecated'. 

### ISSUE THREAD

**Issue by b9Joker108** [ivam3/i-Haklab#14]
#Spanish (translated from English by Google Translate):

Hola

Acabo de instalar y actualizar `i-Haklab` y estoy aprendiendo a manejarlo. Ahora, tan pronto como comienzo una nueva sesión de Termux, soy llevado inmediatamente a un shell "fish" con el portal shell "i-Haklab v. 3.8". Tomo nota de la contraseña predeterminada, la ingreso y la uso sin problemas, y luego puedo generar mi shell `zsh` o `bash` habitual. Pero parece que no puedo ejecutar `i-Haklab` desde ningún shell: `fish`, `zsh` o `bash` una vez que salgo del portal de shell predeterminado. Solo puedo acceder al portal de shell `i-Haklab` de forma predeterminada, al iniciar inmediatamente una nueva sesión de shell. ¿Cómo puedo habilitarlo en mi entorno Termux para ejecutar `i-Haklab` desde cualquier shell en el que me encuentre?

Además, tengo un problema con `chatGPT` en `i-Haklab` después de agregar mi clave API Open AI, el error dice: "El modelo `text-davinci-003` ha quedado obsoleto". Creo que de alguna manera necesito cambiar un poco el modelo en un archivo de configuración, pero no estoy seguro de cómo hacerlo. Mi clave API actualmente está configurada en el modelo: GPT-4-1106-preview. ¿Dónde actualizo esto?

Aprecio que estés ocupado y tu trabajo, que es inspirador, pero realmente agradecería que me ayudaras cuando tengas algo de tiempo.

agradeciendo de antemano
Beauford

#English:

Hello

I have just installed and updated `i-Haklab` and I am learning my way around it. Now, as soon as I start a new Termux session, I am taken immediately to a `fish` shell with the `i-Haklab v. 3.8` shell portal. I note the default password and I enter and use that just fine, and am then able to spawn my usual `zsh` shell or `bash` shell. But I cannot seem to run `i-Haklab` from any shell: `fish`, `zsh` or `bash` once I have left the default shell portal. I can only access the `i-Haklab` shell portal by default, upon immediately starting a new shell session. How can I enable it in my Termux environment to run `i-Haklab` from whatever shell I am in? 

In addition, I have an issue with `chatGPT` in `i-Haklab` after adding my Open AI API key, the error says: "The model `text-davinci-003` has been deprecated'." I think somehow I need to change the model on a config file somewhat, but I am not sure how to do that. My API key is currently set to the model: GPT-4-1106-preview. Where do I update this?

I appreciate you are busy and your work, which is inspiring, but I would really appreciate some assistance when you have some time.

Thanking you in anticipation
Beauford
[https://t.me/hummingbird108](https://t.me/hummingbird108)

**Comment by b9Joker108** [comment]
![Screenshot_20240109_161220_Termux](https://github.com/ivam3/i-Haklab/assets/147242971/40a19056-8817-473c-bcfe-720452cf3c28)

**Comment by ivam3** [comment]
It was fixed on the last update
