### ISSUE TITLE
i-Haklab

### ISSUE THREAD

**Issue by Ramses123456** [ivam3/i-Haklab#7]

**Comment by Ramses123456** [comment]
Hola 👋 Ivan yo asistía a tus envivo de telegram y también apoyaba a la comunidad
Pero tiempo pasado 
Perdóname pero los comandos para la instalación de i-Haklab¿ me parece que á actualizado?
Bueno ese era mi pregunta
Feliz año 🎉 nuevo

**Comment by fckup** [comment]
Sorry I only speak English 🙂 --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 1/5/23, 5:13 AM Ramses123456 ***@***.***> wrote:

   
  Hola 👋 Ivan yo asistía a tus envivo de telegram y también apoyaba a la comunidad Pero tiempo pasado Perdóname pero los comandos para la instalación de i-Haklab¿ me parece que á actualizado? Bueno ese era mi pregunta Feliz año 🎉 nuevo

**Comment by ivam3** [comment]
Gracias por el apoyo bro.

Los pasos de instalación de i-Haklab están en el README.md del proyecto. De igual forma puedes asistir al grupo de apoyo en [Telegram](https://t.me/Ivam3by_Cinderella)

**Comment by fckup** [comment]
Me las arreglé para instalarlo y es muy bueno. Intentaré usar la traducción automática para todas las cosas nuevas que pones en Telegram. Estoy aprendiendo lentamente. soy un gran apoyo del pensamiento libre contra el sistema!! mucho respeto de su amigo en Australia.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 1/14/23, 12:46 PM Ivam3 ***@***.***> wrote:

   
  Gracias por el apoyo bro. 
  Los pasos de instalación de i-Haklab están en el README.md del proyecto. De igual forma puedes asistir al grupo de apoyo en Telegram

**Comment by ivam3** [comment]
Thank you so much bro ... can I Invite you to our [Telegram group](https://t.me/Ivam3by_Cinderella) ? I bring asistence there in Spanish and English too

**Comment by fckup** [comment]
Yeah sure ill join it. English help would be great.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 1/18/23, 12:35 PM Ivam3 ***@***.***> wrote:

   
  Thank you so much bro ... can I Invite you to our Telegram group ? I bring asistence there in Spanish and English too
